/* Exemplo de Programa na linguagem L */

integer i, j = -2;
boolean b, c = true;
string s, t = 'Hello';
byte by, te = 255;

/* Programa Principal */
main
  i = (i * (j - i) + te / j * by) - (10 / 2);
  j = by + 256;
  te = 254 * 0h22;
  te = 0h44 + 0;
  te = by + 0hff;
  te = by - 1;
  i = te;
  ;
  writeln('Oi' + ' ' + 'Tudo bom?');
  while('Oi' == 'Oi') begin
     if(not (478 < 4) and (6 > 9) or not not (789 / 0 != 1 * 2) and b or not ('a' + 'c' == 'b')) then;
  end
end


